# Traceability Tool
# Configuration for running with docker compose 

version: '3'

services:
  traceability_db:
    image: mysql:latest
    container_name: dbTraceability
    environment:
      MYSQL_DATABASE: dbTraceability
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3326:3306"
    volumes:
      - .\Doc\DataBase\dbTraceability:/docker-entrypoint-initdb.d